### ISSUE TITLE
[Fix] 2024.09.20 QA 및 수정

### ISSUE THREAD

**Issue by Due-IT** [pknu-wap/WABI-BE#10]
## 💥이슈 설명
- 2024.09.20 회의에서 나온 수정사항을 고칩니다.

## 📚할 일 목록
- 체크인 명단 확인시 중복되는 이름은 하나로
- 밴드 상세 정보 가져오기 api 추가
- 밴드 테이블에 메모 칼럼 추가
  - 밴드 수정시에도 메모 수정할 수 있게
- 밴드에 학생 넣을때 중복 검사 로직 수정
- Swagger 설명 추가

**Comment by pinpolhoxx** [comment]
try this
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II

Password: changeme

you may need to install the c compiler
